# Generated by Django 2.2.8 on 2020-02-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='age',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
